### ISSUE TITLE
Octopus 3.1.2

### ISSUE THREAD

**Issue by tmurfin** [bitfocus/companion-module-noismada-octopuslistener#1]
The does not work with the new version of octopus, the command syntax has changed

**Comment by JeffreyDavidsz** [comment]
Do you have the syntax? Or can you get it?

**Comment by tmurfin** [comment]
Here is a pdf with the control syntax for the new version of octopus

**Comment by tmurfin** [comment]
[Octopus 3.1.0 Control Protocol.pdf](https://github.com/bitfocus/companion-module-octopusapp/files/3794287/Octopus.3.1.0.Control.Protocol.pdf)

**Comment by JeffreyDavidsz** [comment]
Ok, so I've added the option to choose between free/paid in the instance config. I only checked is the commands according to the protocols are being send, not against the app. If you could test that please? It's in the latest build (somewhere between now and 15min)

**Comment by tmurfin** [comment]
Sorry for the delay, It is working great. Both preset recall and device enable/disable commands are properly working. Thanks for the quick fix.
